{% set name = "vaex-arrow" %}
{% set version = "0.4.1" %}
{% set sha256 = "42c1af347403d199ee673af07ad622d5ebf040f04c6ce63798206e4dd7a28737" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  preserve_egg_dir: True
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - vaex-core >=0.4.2
    - matplotlib >=1.3.1
    - pillow
    - pyarrow

test:
  imports:
    - vaex_arrow

about:
  home: https://www.github.com/maartenbreddels/vaex
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Arrow support for vaex
  description: |
    Arrow support for vaex (out of core dataframes)

extra:
  recipe-maintainers:
    - maartenbreddels
