{% set name = "vaex-arrow" %}
{% set version = "0.5.1" %}
{% set sha256 = "993e8b99a0cf1feb54fb91545788b215348fa2ac6c308dc75ffd0b034bb27fb0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  preserve_egg_dir: true
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - vaex-core >=2.0.0,<3
    - matplotlib-base >=1.3.1
    - pillow
    - pyarrow >=0.17

test:
  imports:
    - vaex_arrow

about:
  home: https://www.github.com/maartenbreddels/vaex
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Arrow support for vaex
  description: |
    Arrow support for vaex (out of core dataframes)

extra:
  recipe-maintainers:
    - maartenbreddels
