travis:
  secure:
    BINSTAR_TOKEN: JLhxHBqerCxAen4tabpa4vP6Yma3um6yWjocPLVWeZGcgxrKGBB7I/ihP3h8uoKPNFl7x5rmdhq5IB+s1GvOM+dU1uNcIFeQBytu52b/9yNOBNboKBwdUK744c+UUrP5PeOXqIclKnUgv7BXBTUPShedcY7DDPZVHUG0YTk31axjtNu3idt9FAYlm01wmAwh8PIHIqaWXwzH6UzZaIG9Mss77wgsKzUshnQnoRJpmC0gC3zFtpvzRb9o8Dk3mTYIAZqJkshjcs0BfIDwk6i2xpLiooSGKzfLD+HoOHRKnB25VNCPeck73C2ano2d/U4CyKvS+XbunMqjkqpOUDgl1O5rUUeB85bJoW5dlSlynFa/E288S/5vfOhn4PEz3R8hi0y2DDUDsbo7ixx1sIlCViaimjW9YCnt3iAtuljLKjs/6H5Ouz+izsjaBCLiZcK8b2PnrRWlprm1xOi3l3h0MLXKQfF1ip0+V43ZnY+Jqi5Mh8f2Lgn6madO+kqIeWlo9bnl1gO6aRSiYg7L2V2DSbGsUNWyHlPuK9y1EjhdUZrIAqQA0vXCcxMuNSZxYrtqDbWS7DA1ORp4ZSaudOsS1rlUBaTOxukmMYE6nQTOZKdUYBF6EDHLcgTHcS1wYruR8GT5pK99CGOBEP7ADJsm2q6fV3akTonDLNe7FDhmeyI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
